version: '3'
services:
    web:
        build: .
        # command: 'node index.js'
        # restart: always
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment: 
            - MYSQL_HOST=db
    db:
        build: ./db
        ports: 
            - "3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - mysql_data:/var/lib/mysql
volumes:
  mysql_data: