version: '3'
services:
    web:
        build: .
        command: 'node index.js'
        ports:
            - "3000:3000"
        restart: always
        depends_on:
            - db
        environment: 
            - MYSQL_HOST=db
    db:
        build: ./db
        ports: 
            - "3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - mysql_data:/var/lib/mysql
volumes:
  mysql_data: